version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - APP_HOST=${APP_HOST}
        - APP_ACCESS_TOKEN_EXPIRE=${APP_ACCESS_TOKEN_EXPIRE}
    ports:
      - "3000:3000"
  backend:
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_ACCESS_TOKEN_EXPIRE: ${APP_ACCESS_TOKEN_EXPIRE}
  postgres:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - app-data:/var/lib/postgresql/${DB_NAME}/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    
volumes:
  app-data: