CREATE TABLE permissions (
  id SERIAL PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  text VARCHAR(30) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  last_updated_by INT REFERENCES users(id),
  deleted_at TIMESTAMP WITH TIME ZONE
);